apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-nginx-multitool
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          name: port-nginx
      - name: multitool
        image: wbitt/network-multitool    # https://github.com/wbitt/Network-MultiTool
        ports:
        - containerPort: 8080
          name: port-multitool
        env:
          - name: HTTP_PORT
            value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-multitool
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: port-nginx
      port: 9001
      nodePort: 30080
      targetPort: port-nginx
    - name: port-multitool
      port: 9002
      nodePort: 30090
      targetPort: port-multitool
  type: NodePort
