apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-nginx-with-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-init
  template:
    metadata:
      labels:
        app: nginx-init
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      initContainers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'until nslookup svc-nginx.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for svc-nginx; sleep 1; done']
