apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-multitool
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: port-nginx
      port: 80
    - name: port-multitool
      port: 1180
