apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-multitool
spec:
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
          - name: varlog-volume
            mountPath: /var/logk8s
      volumes:
      - name: varlog-volume
        hostPath:
          path: /var/log