{
 "title": "Test dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Used %"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{instance=\"192.168.1.125:9100\"}",
     "legendFormat": "LoadAverage 1"
    },
    {
     "expr": "node_load5{instance=\"192.168.1.125:9100\"}",
     "legendFormat": "LoadAverage 5"
    },
    {
     "expr": "node_load15{instance=\"192.168.1.125:9100\"}",
     "legendFormat": "LoadAverage 15"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_memory_MemFree_bytes[1m]) + avg_over_time(node_memory_Cached_bytes[1m]) + avg_over_time(node_memory_Buffers_bytes[1m])) / avg_over_time(node_memory_MemTotal_bytes[1m])) * 100",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"192.168.1.125:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_free_bytes{instance=\"192.168.1.125:9100\"} / node_filesystem_size_bytes{instance=\"192.168.1.125:9100\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}